import type { RouteRecordRaw } from 'vue-router';
import { ENGLISH_CONTENT_PAGES } from '@/i18n/catalog';

export const englishPageLoaders = {
  'en-complexity': () => import('./Complexity.vue'),
  'en-paths': () => import('./Paths.vue'),
  'en-array': () => import('./Array.vue'),
  'en-link': () => import('./LinkedList.vue'),
  'en-stack': () => import('./Stack.vue'),
  'en-queue': () => import('./Queue.vue'),
  'en-tree': () => import('./Tree.vue'),
  'en-heap': () => import('./Heap.vue'),
  'en-hash': () => import('./HashTable.vue'),
  'en-graph': () => import('./Graph.vue'),
  'en-trie': () => import('./Trie.vue'),
  'en-union-find': () => import('./UnionFind.vue'),
  'en-lru': () => import('./LruCache.vue'),
  'en-skip-list': () => import('./SkipList.vue'),
  'en-segment-tree': () => import('./SegmentTree.vue'),
  'en-b-tree': () => import('./BPlusTree.vue'),
  'en-bloom-filter': () => import('./BloomFilter.vue'),
  'en-cocktail-sort': () => import('./CocktailSort.vue'),
  'en-bitonic-sort': () => import('./BitonicSort.vue'),
  'en-selection-sort': () => import('./SelectionSort.vue'),
  'en-insertion-sort': () => import('./InsertionSort.vue'),
  'en-binary-insertion-sort': () => import('./BinaryInsertionSort.vue'),
  'en-shell-sort': () => import('./ShellSort.vue'),
  'en-top-down-merge-sort': () => import('./TopDownMergeSort.vue'),
  'en-three-way-quick-sort': () => import('./ThreeWayQuickSort.vue'),
  'en-dual-pivot-quick-sort': () => import('./DualPivotQuickSort.vue'),
  'en-radix-sort': () => import('./RadixSort.vue'),
  'en-bucket-sort': () => import('./BucketSort.vue'),
  'en-floyd-warshall': () => import('./FloydWarshall.vue'),
  'en-scc': () => import('./StronglyConnectedComponents.vue'),
  'en-two-sat': () => import('./TwoSat.vue'),
  'en-max-flow': () => import('./MaxFlow.vue'),
  'en-hungarian': () => import('./BipartiteMatching.vue'),
  'en-lca': () => import('./LowestCommonAncestor.vue'),
  'en-euler-path': () => import('./EulerianPath.vue'),
  'en-complete-knapsack': () => import('./UnboundedKnapsack.vue'),
  'en-coin-change': () => import('./CoinChange.vue'),
  'en-stone-merge': () => import('./StoneMerging.vue'),
  'en-tsp': () => import('./TravelingSalesperson.vue'),
  'en-tree-dp': () => import('./TreeDynamicProgramming.vue'),
  'en-digit-dp': () => import('./DigitDp.vue'),
  'en-reroot-dp': () => import('./RerootingDp.vue'),
  'en-permutations': () => import('./Permutations.vue'),
  'en-combination-sum': () => import('./CombinationSum.vue'),
  'en-number-of-islands': () => import('./NumberOfIslands.vue'),
  'en-word-search': () => import('./WordSearch.vue'),
  'en-sudoku': () => import('./Sudoku.vue'),
  'en-astar': () => import('./AStar.vue'),
  'en-boyer-moore': () => import('./BoyerMoore.vue'),
  'en-suffix-array': () => import('./SuffixArray.vue'),
  'en-lcp-array': () => import('./LcpArray.vue'),
  'en-aho-corasick': () => import('./AhoCorasick.vue'),
  'en-z-function': () => import('./ZFunction.vue'),
  'en-linear-sieve': () => import('./LinearSieve.vue'),
  'en-fast-power': () => import('./BinaryExponentiation.vue'),
  'en-ext-gcd': () => import('./ExtendedEuclidean.vue'),
  'en-crt': () => import('./ChineseRemainderTheorem.vue'),
  'en-euler-phi': () => import('./EulerTotient.vue'),
  'en-miller-rabin': () => import('./MillerRabin.vue'),
  'en-fft': () => import('./FastFourierTransform.vue'),
  'en-pollard-rho': () => import('./PollardRho.vue'),
  'en-rotating-calipers': () => import('./RotatingCalipers.vue'),
  'en-segment-intersection': () => import('./SegmentIntersection.vue'),
  'en-bentley-ottmann': () => import('./BentleyOttmann.vue'),
  'en-rotated-search': () => import('./RotatedArraySearch.vue'),
  'en-binary-answer': () => import('./BinarySearchAnswer.vue'),
  'en-ternary-search': () => import('./TernarySearch.vue'),
  'en-quick-sort': () => import('./QuickSort.vue'),
  'en-binary-search': () => import('./BinarySearch.vue'),
  'en-dijkstra': () => import('./Dijkstra.vue'),
  'en-knapsack': () => import('./Knapsack.vue'),
  'en-kmp': () => import('./Kmp.vue'),
  'en-fenwick': () => import('./Fenwick.vue'),
  'en-convex-hull': () => import('./ConvexHull.vue'),
  'en-bubble-sort': () => import('./BubbleSort.vue'),
  'en-merge-sort': () => import('./MergeSort.vue'),
  'en-heap-sort': () => import('./HeapSort.vue'),
  'en-counting-sort': () => import('./CountingSort.vue'),
  'en-binary-bounds': () => import('./BinaryBounds.vue'),
  'en-kruskal': () => import('./Kruskal.vue'),
  'en-prim': () => import('./Prim.vue'),
  'en-bellman-ford': () => import('./BellmanFord.vue'),
  'en-topological-sort': () => import('./TopologicalSort.vue'),
  'en-closest-pair': () => import('./ClosestPair.vue'),
  'en-edit-distance': () => import('./EditDistance.vue'),
  'en-lcs': () => import('./LongestCommonSubsequence.vue'),
  'en-lis': () => import('./LongestIncreasingSubsequence.vue'),
  'en-n-queens': () => import('./NQueens.vue'),
  'en-subsets': () => import('./Subsets.vue'),
  'en-maze': () => import('./Maze.vue'),
  'en-rabin-karp': () => import('./RabinKarp.vue'),
  'en-manacher': () => import('./Manacher.vue'),
  'en-sieve-of-eratosthenes': () => import('./SieveOfEratosthenes.vue'),
  'en-gcd': () => import('./EuclideanAlgorithm.vue'),
} as const;

export type EnglishContentRouteName = keyof typeof englishPageLoaders;

function isEnglishContentRouteName(name: string): name is EnglishContentRouteName {
  return name in englishPageLoaders;
}

export const englishContentRoutes: readonly RouteRecordRaw[] = Object.freeze(
  ENGLISH_CONTENT_PAGES.map((page) => {
    const name = page.en.name;
    if (!isEnglishContentRouteName(name)) {
      throw new Error(`English page loader is missing: ${name}`);
    }
    return {
      path: page.en.path,
      name,
      component: englishPageLoaders[name],
    } satisfies RouteRecordRaw;
  }),
);
